### ISSUE TITLE
The problem

### ISSUE THREAD

**Issue by Edmonas2011** [0xf15/change-username-tiktok#47]
Enter session ID: ********************
Your current TikTok username is: mxzeko
Enter the new username you wish to set: привет пупсик))
Traceback (most recent call last):
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/site-packages/urllib3/connection.py", line 196, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 7] No address associated with hostname

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/site-packages/urllib3/connectionpool.py", line 490, in _make_request
    raise new_e
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/site-packages/urllib3/connection.py", line 615, in connect
    self.sock = sock = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/site-packages/urllib3/connection.py", line 203, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x6dbc1c5e10>: Failed to resolve 'api.tiktokv.com' ([Errno 7] No address associated with hostname)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.tiktokv.com', port=443): Max retries exceeded with url: /aweme/v1/commit/user/?aid=364225&residence=&device_id=663726348251&version_name=1.1.0&os_version=17.4.1&iid=529711693443&app_name=tiktok_snail&locale=en&ac=4G&sys_region=SA&version_code=1.1.0&channel=App%20Store&op_region=SA&os_api=18&device_brand=iPad&idfv=16045E07-1ED5-4350-9318-77A1469C0B89&device_platform=iPad&device_type=iPad13,4&carrier_region1=&tz_name=Asia/Riyadh&account_region=sa&build_number=11005&tz_offset=10800&app_language=en&carrier_region=&current_region=&aid=364225&mcc_mnc=&screen_width=1284&uoo=1&content_language=&language=en&cdid=B75649A607DA449D8FF2ADE97E0BC3F1&openudid=7b053588b18d61b89c891592139b68d918b44933&app_version=1.1.0 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x6dbc1c5e10>: Failed to resolve 'api.tiktokv.com' ([Errno 7] No address associated with hostname)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 31, in <module>
    start(fakepyfile,mainpyfile)
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 30, in start
    exec(open(mainpyfile).read(),  __main__.__dict__)
  File "<string>", line 277, in <module>
  File "<string>", line 268, in main
  File "<string>", line 246, in change_username
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.tiktokv.com', port=443): Max retries exceeded with url: /aweme/v1/commit/user/?aid=364225&residence=&device_id=663726348251&version_name=1.1.0&os_version=17.4.1&iid=529711693443&app_name=tiktok_snail&locale=en&ac=4G&sys_region=SA&version_code=1.1.0&channel=App%20Store&op_region=SA&os_api=18&device_brand=iPad&idfv=16045E07-1ED5-4350-9318-77A1469C0B89&device_platform=iPad&device_type=iPad13,4&carrier_region1=&tz_name=Asia/Riyadh&account_region=sa&build_number=11005&tz_offset=10800&app_language=en&carrier_region=&current_region=&aid=364225&mcc_mnc=&screen_width=1284&uoo=1&content_language=&language=en&cdid=B75649A607DA449D8FF2ADE97E0BC3F1&openudid=7b053588b18d61b89c891592139b68d918b44933&app_version=1.1.0 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x6dbc1c5e10>: Failed to resolve 'api.tiktokv.com' ([Errno 7] No address associated with hostname)"))

[Program finished]

**Comment by andrewzaycew** [comment]
Оператор блокирует мб хост

**Comment by andrewzaycew** [comment]
Прпробуй впн

**Comment by Edmonas2011** [comment]
С ВПН ом такая проблема Enter session ID: ************************
Your current TikTok username is: mxzeko
Enter the new username you wish to set: привет пупс))
Failed to change username: {"log_pb":{"impr_id":"20240814045305E395E78F001CCD0248BE"},"status_code":3002284,"status_msg":"Slow down, you are editing too fast."}
telegram @harbi

[Program finished]

**Comment by andrewzaycew** [comment]
Другой акк юзай, если ты пытался сменить на аккиче ник начиная со вчера 13:00 по мск, то на жтом акке ты НИКАК не сможешь сменить

**Comment by andrewzaycew** [comment]
> > Другой акк юзай, если ты пытался сменить на аккиче ник начиная со вчера 13:00 по мск, то на жтом акке ты НИКАК не сможешь сменить
> 
> yo I just made a new account and tried it on a new one and I also have the same error as edmonas. Did they patch it maybe?
> 
> rus: yo Я только что создал новый аккаунт и попробовал на новом, и у меня та же ошибка, что и у edmonas. Может, они ее исправили?

Неа, ты если вчера пробывал сменить ник, то ты уже больше на этом аккаунте не сменишь, делай новый

**Comment by andrewzaycew** [comment]
> Да, я только что создал новую учетную запись, и она все еще выдает мне ту же ошибку. Я не знаю, поможет ли это, но я использовал vpn, когда использовал инструмент, чтобы увидеть, может быть, это из-за того, что у меня ограниченная скорость или что-то в этом роде, но у меня все еще есть эта ошибка

Хм, щас проверю

**Comment by andrewzaycew** [comment]
> Спасибо, еще одна вещь: я также попытался повторно войти в систему, чтобы сгенерировать новый идентификатор сеанса в существующей учетной записи, которая не является новой, и после нескольких попыток мне удалось изменить имя один раз после двух ошибок, а затем это начало происходить снова, так что да, я не уверен

Все работает
Не знаю с чем у тебя это связано, у меня такое же было, я просто сменил аккаунт

**Comment by andrewzaycew** [comment]
> Извините, на самом деле я использую Google Translate, поэтому перевод может быть неточным, хаха

Я все понимаю, я знаю английский неплохо, но говорить я на нем не могу, хах

**Comment by andrewzaycew** [comment]
> У вас это сработало?

Да

**Comment by andrewzaycew** [comment]
> Понятно хаха, я не уверен, может мой ip как-то заблокирован? VPN влияет только на мой браузер, а не на весь компьютер

Недавно у человека в другом issue была ьакая же проблема, попробывал другой аккаунт, и все заработало!
